name: Issue Control

on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: |
      github.event.comment.author_association == 'COLLABORATOR'
      && github.event.issue.pull_request != 0
      && github.event.issue.closed_at == 0
      && github.event.issue.locked == 0
      && github.event.comment.body == 'run tests'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the head branch of the PR
        run: |
          branch=$(curl ${{ github.event.issue.pull_request.url }} | jq -r '.head.ref')
          git clone --branch=$branch --depth=1 ${{ github.repositoryUrl }} .

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Test
        run: |
          npm test
          ec=$?
          echo "::set-env name=EXIT_CODE::$ec"

      - name: Report back to the comment thread with the results
        if: always()
        run: |
          workflowUrl=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          (( EXIT_CODE == 0 )) && textStatus='**Passed**' || textStatus='**Failed**'
          data='{ "body": "['$textStatus']('$workflowUrl')" }'

          response=$(curl -sSL --request POST --url ${{ github.event.issue.comments_url }} \
            --header 'authorization: Bearer ${{ github.token }}' \
            --header 'content-type: application/json' \
            --data "$data" -o /dev/null -w '%{http_code}\n')
          (( response == 201 ))

