name: check

on:
  pull_request:
    branches: 'release'

jobs:
  check-version:
    if: |
      github.event.action == 'opened' || github.event.action == 'reopened'

    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        run: |
          echo "::set-env name=VERSION::${{ github.event.pull_request.head.ref }}"

      - name: Clone the branch
        run: |
          git clone --branch=$VERSION --depth=1 ${{ github.repositoryUrl }} .

      - name: Get the live package version
        run: |
          repoName=$(awk '/name/ { print $3 }' RS=',\n' package.json)
          packageVer=$(npm view ${repoName//\"/} version)

          echo "::set-env name=PACKAGE_VER::$packageVer"

      - name: Check that the version is not the same as the live package version
        run: |
          [[ $VERSION != $PACKAGE_VER ]]

      - name: Check that the version is a valid semver string
        run: |
          npx semver $VERSION

      - name: Check that the version is greater than the live package version
        run: |
          sorted=$(npx semver $VERSION $PACKAGE_VER)

          checkSort="$PACKAGE_VER
          $VERSION"

          echo Sorted:
          echo $sorted
          echo
          echo Checked Sort:
          echo $checkSort

          # Verify that the order is correct
          [[ $sorted == $checkSort ]]

