name: published

on:
  pull_request:
    branches:
      - 'release'

jobs:
  publish:
    if: |
      github.event.action == 'closed' && github.event.merged == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the release branch
        run: |
          git clone --branch=release --depth=1 ${{ github.repositoryUrl }} .

      - name: Initialize docs directory
        run: |
          rm -rf docs/*
          git clone --depth=1 --branch=master ${{ github.repositoryUrl }} docs
          rm -rf docs/*

      - name: Generate docs
        run: |
          npm ci
          npm run gen-docs

      - name: Set version on release branch and push
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@noreply.github.com

          tag=$(npm version ${{ github.event.pull_request.head.ref }})
          echo "::set-env name=VERSION::$tag"

          git push https://${{ github.actor }}:${{ secrets.re_push }}@github.com/${{ github.repository }}.git release
          git push $tag

      - name: Publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.npm_token }}"
          npm publish

      - name: Update the live docs
        run: |
          cd docs
          git add --all
          git commit -m "Updated docs"
          git push


