name: publish

on:
  push:
    branches:
      - 'prod'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install and publish
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Initialize docs directory
        run: |
          git clone --depth=1 --branch=master $REPO_URL docs
          rm -rf docs/*
        env:
          REPO_URL: ${{ github.repositoryUrl }}

      - name: Generate docs
        run: |
          npm run gen-docs

      - name: Update the live docs
        run: |
          cd docs
          git add --all
          git commit -m "Updated docs"
          git push

