name: test

on:
  push:
    branches:
      - 'release'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the production branch
        run: |
          git clone --branch=release --depth=1 ${{ github.repositoryUrl }} .

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Test
        run: |
          npm test
        env:
          CI: true

